services:
  mediajournal.web:
    image: mediajournal.web
    build:
      context: .
      dockerfile: MediaJournal.Web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - sqlite-data:/app/Data

volumes:
  sqlite-data: